spring.application.name=reactive-project-rest
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/projects
spring.r2dbc.username=postgres
spring.r2dbc.password=admin
logging.level.root=INFO
# Opcjonalnie poziom na DEBUG
logging.level.com.project=DEBUG
# Opcjonalnie drukowanie zapytan SQL generowanych przez Spring Data R2DBC
logging.level.org.springframework.r2dbc=DEBUG

# po wystawieniu aplikacji endpoint powinien byc tutaj dostepny
# http://localhost:8080/actuator/prometheus
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.prometheus.metrics.export.enabled=true

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:projects-schema.sql