spring.application.name=reactive-project-rest
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/projects
spring.r2dbc.username=postgres
spring.r2dbc.password=admin
logging.level.root=INFO
# Opcjonalnie poziom na DEBUG
logging.level.com.project=DEBUG
# Opcjonalnie drukowanie zapytan SQL generowanych przez Spring Data R2DBC
logging.level.org.springframework.r2dbc=DEBUG