# Spring DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/projekty
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
# Spring JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Spring Security
spring.security.user.name=admin
spring.security.user.password=admin
# Testowy klucz mo?na wygenerowa? np. za pomoc? https://acte.ltd/utils/randomkeygen (jako Encryption key 256-bit)
jwt.access-secret-key=Xn2r5u8x/A?D(G-KaPdSgVkYp3s6v9y$
jwt.access-token-validity-in-min=15
jwt.refresh-secret-key=2s5v8y/B?E(G+KbPeShVmYq3t6w9z$C&
jwt.refresh-token-validity-in-min=480
# Wlaczenie watkow wirtualnych
spring.threads.virtual.enabled=true
